### ISSUE TITLE
 Empowering Students with DevBucket: A Comprehensive Path to Career Readiness

### ISSUE THREAD

**Issue by habibrahman29** [microsoft/RAG_Hack#136]
### Project Name

DevBucket

### Description

# DevBucket

## Inspiration
As a community-driven individual, I understand the challenges faced by students in my community, especially those unsure about their career paths. Many students spend unproductive time in college, while those with passion lack a structured roadmap for skill development to become job-ready. Furthermore, in our tier-3 colleges, internship opportunities are scarce due to remote locations. To address these challenges, my friend and I built **DevBucket**, a solution to help students become job-ready.

## What it Does
DevBucket is a machine learning-based web application that empowers students to build their core skills and become job-ready. The platform offers:
- **Mentorship**: Students receive guidance from a machine learning model and professional community members.
- **Roadmaps**: A structured learning path across different domains.
- **Internship Opportunities**: Real-world projects to enhance skills.

Our platform helps students access the latest learning resources and hands-on projects to refine their technical abilities.

## How We Built It
DevBucket utilizes a **microservice architecture**. I focused on **Python, Flask, and Azure Machine Learning**, while my friend handled the front-end with **Java**. Here's a breakdown of our architecture:
- **ML/AI**: Using **Azure ML** and **Azure AI services**, I deployed a Random Forest machine learning model, creating a REST endpoint. This endpoint provides career mentorship guidance based on user data. For the chatbot, we used **GPT-3.5-Turbo** along with **RAG** and **OpenAI embeddings** to retrieve information from books uploaded by students.
- **Web Application**: The backend was developed using **Flask** and **Springboot**. The roadmap and internship sections were built in Java, while the **NoCodePortfolio** section was handled in Python (Flask). Data is stored in **MySQL**, allowing dynamic fetching of roadmap details.

## Challenges We Faced
- **API limitations**: The OpenAI key had restrictions on queries per minute and token limits for text generation.
- **Azure ML Integration**: Deploying models on Azure ML and integrating them with Java applications was challenging.
- **Chatbot Integration**: Linking the chatbot seamlessly to the application posed technical hurdles.
- **Dynamic Data Fetching**: Retrieving data dynamically from the MySQL database for the roadmap section was complex.

## Accomplishments
We are proud of creating **DevBucket**, a complete solution for students at smaller colleges. Our key accomplishments include:
- **Comprehensive Solution**: Providing mentorship, career paths, and internship opportunities.
- **Smart Chatbot**: Quickly retrieves information from uploaded books.
- **Team Collaboration**: Effective teamwork and task management.
- **High Accuracy**: Azure ML services provide career guidance with 96% accuracy.

## What We Learned
This project offered invaluable learning experiences, including:
- **Azure ML Expertise**: Gained proficiency in deploying models and creating endpoints.
- **AI Integration**: Successfully implemented GPT-3.5-Turbo, RAG, and OpenAI embeddings.
- **Team Collaboration**: Worked professionally as a team, solving challenges and integrating components in real-time.

## What's Next
To scale and improve **DevBucket**, we plan to:
- **Enhance Accuracy**: Collect more data to improve our machine-learning model across various domains.
- **Build Partnerships**: Collaborate with organizations to provide more internship opportunities.
- **Expand Reach**: Leverage social media for marketing and explore funding opportunities to scale our project.
- **Ensure Security**: Implement robust security measures to safeguard user data.

### Technology & Languages

- [ ] JavaScript
- [X] Java
- [ ] .NET
- [X] Python
- [X] AI Studio
- [ ] AI Search
- [ ] PostgreSQL
- [ ] Cosmos DB
- [ ] Azure SQL

### Project Repository URL

https://github.com/savageheart/AI-Classroom

### Project Video

https://drive.google.com/file/d/1At9fZYfP25Zo6IZNulAB4EPrwBNnetXh/view?usp=sharing

### Team Members

savageheart, habibrahman29

**Comment by pamelafox** [comment]
There seems to be a lot of similarity between your project and https://github.com/XFarooqi/DevHub-AI-Classroom/ , are they also a collaborator of yours?
